import React from 'react';
import { Box, Typography, Grid } from '@mui/material';
import { PanelBar, PanelBarItem } from '@progress/kendo-react-layout';
import { Scheduler } from '@progress/kendo-react-scheduler';
import { DatePicker } from '@progress/kendo-react-dateinputs';
import { Notification } from '@progress/kendo-react-notification';
import { Chart, ChartSeries, ChartSeriesItem, ChartCategoryAxis, ChartCategoryAxisItem, ChartValueAxis, ChartValueAxisItem } from '@progress/kendo-react-charts';
import { PatientViewType } from '../Layout';
import { BentoCard } from '../../components/BentoCard';

// Icons for Bento Grid
import CalendarMonthIcon from '@mui/icons-material/CalendarMonth';
import ChildFriendlyIcon from '@mui/icons-material/ChildFriendly';
import HealingIcon from '@mui/icons-material/Healing';
import SchoolIcon from '@mui/icons-material/School';
import MedicationIcon from '@mui/icons-material/Medication';
import VisibilityIcon from '@mui/icons-material/Visibility';
import HealthAndSafetyIcon from '@mui/icons-material/HealthAndSafety';


interface PatientDashboardProps {
  onNavigate: (view: PatientViewType) => void;
}

const PatientDashboard: React.FC<PatientDashboardProps> = ({ onNavigate }) => {
  const [selectedDate, setSelectedDate] = React.useState(new Date());
  
  return (
    <Box sx={{ overflowX: 'hidden' }}>
        <Typography variant="h5" sx={{ mb: 1 }}>Welcome to Your Health Hub</Typography>
        <Typography variant="body1" color="text.secondary" sx={{ mb: 4}}>
            Your comprehensive toolkit for managing your health, powered by AI.
        </Typography>
        
        <Box sx={{ mb: 3, display: 'flex', gap: 2, alignItems: 'center' }}>
          <Typography variant="subtitle1">Select Date:</Typography>
          <DatePicker 
            value={selectedDate} 
            onChange={(e) => setSelectedDate(e.value || new Date())}
          />
        </Box>

        <PanelBar style={{ marginBottom: '20px' }}>
          <PanelBarItem title="Health Modules" expanded>
            <Box sx={{ p: 2 }}>
            <Grid item xs={12} sm={6} md={4}>
                <BentoCard
                    title="Menstrual & Reproductive Health"
                    description="Track your cycle, predict ovulation, and get AI-powered insights on symptoms."
                    icon={<CalendarMonthIcon />}
                    onClick={() => onNavigate('menstrual-tracker')}
                    variant="large"
                />
            </Grid>
            <Grid item xs={12} sm={6} md={4}>
                <BentoCard
                    title="Pregnancy & Postpartum"
                    description="Follow your baby's weekly growth, monitor your health, and prepare for postpartum recovery."
                    icon={<ChildFriendlyIcon />}
                    onClick={() => onNavigate('pregnancy-tracker')}
                    variant="large"
                />
            </Grid>
            <Grid item xs={12} sm={6} md={4}>
                <BentoCard
                    title="AI Symptom Checker"
                    description="Describe your symptoms to get a preliminary AI analysis and suggested next steps."
                    icon={<HealingIcon />}
                    onClick={() => onNavigate('symptom-checker')}
                    variant="large"
                />
            </Grid>
             <Grid item xs={12} sm={6} md={4}>
                 <BentoCard
                    title="Personalized Health Education"
                    description="Ask any health question and get clear, illustrated answers generated by AI."
                    icon={<SchoolIcon />}
                    onClick={() => onNavigate('health-education')}
                    variant="large"
                />
            </Grid>
            <Grid item xs={12} sm={6} md={4}>
                <BentoCard
                    title="Medication Helper"
                    description="Upload or type your prescription to get a simple, clear explanation of your medication."
                    icon={<MedicationIcon />}
                    onClick={() => onNavigate('medication-helper')}
                    variant="large"
                />
            </Grid>
            <Grid item xs={12} sm={6} md={4}>
                <BentoCard
                    title="Annotate My Scan"
                    description="Learn about your body. Upload a scan to see an AI-powered anatomical guide."
                    icon={<VisibilityIcon />}
                    onClick={() => onNavigate('scan-annotator')}
                    variant="large"
                />
            </Grid>
            <Grid item xs={12} sm={6} md={4}>
                <BentoCard
                    title="My AI Health Plan"
                    description="Chat with an AI coach to create and track a personalized wellness plan for your goals."
                    icon={<HealthAndSafetyIcon />}
                    onClick={() => onNavigate('health-plan')}
                    variant="large"
                />
            </Grid>
            </Box>
          </PanelBarItem>
          <PanelBarItem title="Appointments">
            <Box sx={{ p: 2 }}>
              <Scheduler
                data={[]}
                style={{ height: '400px' }}
              />
            </Box>
          </PanelBarItem>
          <PanelBarItem title="Health Analytics">
            <Box sx={{ p: 2 }}>
              <Chart style={{ height: '300px' }}>
                <ChartSeries>
                  <ChartSeriesItem type="line" data={[65, 70, 68, 72, 75, 78, 80]} />
                </ChartSeries>
                <ChartCategoryAxis>
                  <ChartCategoryAxisItem categories={['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul']} />
                </ChartCategoryAxis>
                <ChartValueAxis>
                  <ChartValueAxisItem min={60} max={85} />
                </ChartValueAxis>
              </Chart>
            </Box>
          </PanelBarItem>
        </PanelBar>
        
        <Notification />
    </Box>
  );
};

export default PatientDashboard;